// Base de données des couleurs — Bétonel (Dulux Canada) & Sherwin Williams
// Généré automatiquement — ne pas modifier manuellement
// Source Bétonel: dulux.ca/fr-ca/all-colours (avril 2026)
// Étend window.COULEURS défini dans le HTML principal

(function() {
  // Convertit rgb(r,g,b) en #RRGGBB (pour référence interne)
  // Toutes les valeurs hex ci-dessous sont déjà calculées

  var BETONEL = [
    // === BLANCS & CRÈMES ===
    {code:'DLX1001-1', nom:'Blanc délicat / Delicate White',   hex:'#F1F2EE', source:'Bétonel'},
    {code:'DLX1002-1', nom:'Plume argentée / Silver Feather',  hex:'#EDEBE7', source:'Bétonel'},
    {code:'DLX1007-1', nom:'Willow Springs',                   hex:'#E7E6E0', source:'Bétonel'},
    {code:'DLX1008-1', nom:'Focus',                            hex:'#E5E0D2', source:'Bétonel'},
    {code:'DLX1012-1', nom:'Baie glacée / Icy Bay',            hex:'#E0E5E2', source:'Bétonel'},
    {code:'DLX1013-1', nom:'Radisson',                         hex:'#E5E7E6', source:'Bétonel'},
    {code:'DLX1015-1', nom:'Lait frappé vanille / Vanilla Milkshake', hex:'#F1ECE2', source:'Bétonel'},
    {code:'DLX1021-1', nom:'Gris montagne / Mountain Gray',    hex:'#E8E3DB', source:'Bétonel'},
    {code:'DLX1024-1', nom:'Blanc cassé / Off White',          hex:'#E8E4D6', source:'Bétonel'},
    {code:'DLX1024-2', nom:'Blanc antique / Antique White',    hex:'#E1DACA', source:'Bétonel'},
    {code:'DLX1038-1', nom:'Bruine du soir / Evening Mist',    hex:'#E3E9E8', source:'Bétonel'},
    {code:'DLX1042-1', nom:'Lys calla / Calla Lily',           hex:'#E4EAEd', source:'Bétonel'},
    {code:'DLX1074-1', nom:'Perles et dentelle / Pearls and Lace', hex:'#EEE6DB', source:'Bétonel'},
    {code:'DLX1076-1', nom:'Licorne / Fuzzy Unicorn',          hex:'#EAE3DB', source:'Bétonel'},
    {code:'DLX1084-2', nom:"Poudre d'oignon / Onion Powder",   hex:'#ECE2D4', source:'Bétonel'},
    {code:'DLX1085-2', nom:'Blanc os / Bone White',            hex:'#E4D9C5', source:'Bétonel'},
    {code:'DLX1086-1', nom:'Horseradish',                      hex:'#EEEADD', source:'Bétonel'},
    {code:'DLX1086-2', nom:'Brandied Pears',                   hex:'#EAE2D1', source:'Bétonel'},
    {code:'DLX1086-3', nom:'Almond Cream',                     hex:'#E1CFB2', source:'Bétonel'},
    {code:'DLX1096-2', nom:'Sable du Maroc / Morocco Sand',    hex:'#ECE3CC', source:'Bétonel'},
    {code:'DLX1097-1', nom:'Mousse froide / Cold Foam',        hex:'#E9E5D7', source:'Bétonel'},
    {code:'DLX1097-2', nom:'Vent du sud / Southern Breeze',    hex:'#E4DFD1', source:'Bétonel'},
    {code:'DLX1097-3', nom:'Amande grillée / Toasted Almond',  hex:'#DACFBA', source:'Bétonel'},
    {code:'DLX1098-1', nom:'Peinture au lait / Milk Paint',    hex:'#EFE9D9', source:'Bétonel'},
    {code:'DLX1098-3', nom:'Sand Fossil',                      hex:'#DECFB3', source:'Bétonel'},
    {code:'DLX1100-1', nom:'Nacre / Mother Of Pearl',          hex:'#F2EFE1', source:'Bétonel'},
    {code:'DLX1100-2', nom:'Blanc adobe / Adobe White',        hex:'#F2ECD9', source:'Bétonel'},
    {code:'DLX1102-1', nom:'Pergélisol / Enduring Ice',        hex:'#EBE8DB', source:'Bétonel'},
    {code:'DLX1104-1', nom:'Rocher blanc / White Rock',        hex:'#EEE9D9', source:'Bétonel'},
    {code:'DLX1104-2', nom:'Blanc abbaye / Abbey White',       hex:'#EBE5D0', source:'Bétonel'},
    {code:'DLX1111-1', nom:'Vents des prairies / Prairie Winds', hex:'#E8E6D9', source:'Bétonel'},
    {code:'DLX1112-1', nom:'Petit agneau / Little Lamb',       hex:'#EAE6D7', source:'Bétonel'},
    {code:'DLX1205-1', nom:'Fils de coton / Combed Cotton',    hex:'#F4F0DE', source:'Bétonel'},
    {code:'DLX1207-1', nom:'Beige chandelle / Candlelit Beige', hex:'#F1EDE0', source:'Bétonel'},
    {code:'DLX1208-1', nom:'Accolade',                         hex:'#F1EEE2', source:'Bétonel'},
    {code:'DLX1213-1', nom:'Voile marine / Sail Cloth',        hex:'#F0F0E0', source:'Bétonel'},
    {code:'DLX1214-1', nom:'Pâte à gâteau / Cake Batter',     hex:'#F0EDB7', source:'Bétonel'},
    {code:'DLX1215-1', nom:'Jaune clair / Clear Yellow',       hex:'#F1F1E6', source:'Bétonel'},
    {code:'DLX14-23',  nom:'Edelweiss',                        hex:'#EEE8D9', source:'Bétonel'},
    {code:'DLX18-09',  nom:"Gousse d'ail / Garlic Clove",      hex:'#ECE9DD', source:'Bétonel'},
    {code:'DLX1095-4', nom:'Golden Ecru',                      hex:'#D8C39F', source:'Bétonel'},

    // === GRIS & NEUTRES ===
    {code:'DLX1006-4', nom:'Mercurial',                        hex:'#B6B0A9', source:'Bétonel'},
    {code:'DLX1007-6', nom:'Cool Charcoal',                    hex:'#807B76', source:'Bétonel'},
    {code:'DLX1008-4', nom:'Gray By Me',                       hex:'#A1988B', source:'Bétonel'},
    {code:'DLX1009-3', nom:'Solitary State',                   hex:'#C4C7C4', source:'Bétonel'},
    {code:'DLX1009-4', nom:'Gray Stone',                       hex:'#B7B9B5', source:'Bétonel'},
    {code:'DLX1004-6', nom:'Phantom Hue',                      hex:'#645D5E', source:'Bétonel'},
    {code:'DLX1012-5', nom:'Steeple Gray',                     hex:'#8E9598', source:'Bétonel'},
    {code:'DLX1033-7', nom:'Charcoal Smoke',                   hex:'#474F43', source:'Bétonel'},
    {code:'DLX1039-1', nom:'Ghost Whisperer',                  hex:'#CBD1D0', source:'Bétonel'},
    {code:'DLX1039-2', nom:'Maiden Mist',                      hex:'#B9C0C0', source:'Bétonel'},
    {code:'DLX1039-3', nom:'Mirror Mirror',                    hex:'#A8B0B2', source:'Bétonel'},
    {code:'DLX1039-4', nom:'Pachyderm',                        hex:'#8F989D', source:'Bétonel'},
    {code:'DLX1039-5', nom:'Garrison Gray',                    hex:'#7B8588', source:'Bétonel'},
    {code:'DLX1039-6', nom:'In The Shadows',                   hex:'#656E72', source:'Bétonel'},
    {code:'DLX1039-7', nom:'High Salute',                      hex:'#445056', source:'Bétonel'},
    {code:'DLX1041-1', nom:'Moonlit Snow',                     hex:'#EAEEEC', source:'Bétonel'},
    {code:'DLX1041-2', nom:'City Lights',                      hex:'#DFE6EA', source:'Bétonel'},
    {code:'DLX1041-3', nom:'Billowing Clouds',                 hex:'#D8DEE3', source:'Bétonel'},
    {code:'DLX1041-4', nom:'Blue Dolphin',                     hex:'#BCC5CF', source:'Bétonel'},
    {code:'DLX1041-5', nom:'Quicksilver',                      hex:'#939FA9', source:'Bétonel'},
    {code:'DLX1041-6', nom:'Sheffield Gray',                   hex:'#6B7680', source:'Bétonel'},
    {code:'DLX1038-2', nom:'Dewdrop',                          hex:'#DDE4E3', source:'Bétonel'},
    {code:'DLX1038-3', nom:"Winter's Breath",                  hex:'#D4DDDD', source:'Bétonel'},
    {code:'DLX1038-5', nom:'Feldspar',                         hex:'#858F94', source:'Bétonel'},
    {code:'DLX1038-6', nom:'Lava Gray',                        hex:'#5E686D', source:'Bétonel'},
    {code:'DLX1038-7', nom:'Midnight Hour',                    hex:'#3B484F', source:'Bétonel'},
    {code:'DLX1172-1', nom:'Tempête de neige / Snow Storm',    hex:'#EEEDEA', source:'Bétonel'},
    {code:'DLX1168-1', nom:'Lys lunaire / Moon Lily',          hex:'#E6E6E7', source:'Bétonel'},
    {code:'DLX1171-1', nom:'Plaisir silencieux / Silent Delight', hex:'#E5E7E8', source:'Bétonel'},
    {code:'DLX1179-1', nom:'Matin brumeux / Misty Morn',       hex:'#E7E1E3', source:'Bétonel'},

    // === BRUNS, TAUPES & TERRES ===
    {code:'DLX1021-3', nom:'Discover',                         hex:'#BDB0A0', source:'Bétonel'},
    {code:'DLX1021-5', nom:'Thunderbird',                      hex:'#8C7B6C', source:'Bétonel'},
    {code:'DLX1073-3', nom:'Pale Taupe',                       hex:'#E3D1C8', source:'Bétonel'},
    {code:'DLX1073-4', nom:'Pueblo',                           hex:'#D0BBB0', source:'Bétonel'},
    {code:'DLX1073-5', nom:'Tanglewood',                       hex:'#A58F85', source:'Bétonel'},
    {code:'DLX1073-6', nom:'Derby Brown',                      hex:'#8A7265', source:'Bétonel'},
    {code:'DLX1073-7', nom:'Fudge',                            hex:'#63493E', source:'Bétonel'},
    {code:'DLX1072-4', nom:'Taupe Tapestry',                   hex:'#C3A79A', source:'Bétonel'},
    {code:'DLX1072-5', nom:'Tattered Teddy',                   hex:'#A2806F', source:'Bétonel'},
    {code:'DLX1072-6', nom:'Suede Leather',                    hex:'#896757', source:'Bétonel'},
    {code:'DLX1072-7', nom:'Bird House Brown',                 hex:'#6C483A', source:'Bétonel'},
    {code:'DLX1074-5', nom:'Peppered Pecan',                   hex:'#957D6F', source:'Bétonel'},
    {code:'DLX1074-7', nom:'Little Bear',                      hex:'#604B42', source:'Bétonel'},
    {code:'DLX1075-4', nom:'Thumper',                          hex:'#BDADA4', source:'Bétonel'},
    {code:'DLX1075-5', nom:'Ranch Mink',                       hex:'#968379', source:'Bétonel'},
    {code:'DLX1075-7', nom:'Fudge Truffle',                    hex:'#604A3F', source:'Bétonel'},
    {code:'DLX1084-4', nom:'Happy Trails',                     hex:'#CDB69B', source:'Bétonel'},
    {code:'DLX1084-5', nom:'Coffee Kiss',                      hex:'#B19576', source:'Bétonel'},
    {code:'DLX1084-7', nom:'Maple Syrup',                      hex:'#75583D', source:'Bétonel'},
    {code:'DLX1085-6', nom:'Hat Box Brown',                    hex:'#8F775D', source:'Bétonel'},
    {code:'DLX1095-6', nom:'Chicory',                          hex:'#A78658', source:'Bétonel'},
    {code:'DLX1018-7', nom:'Sarsaparilla',                     hex:'#5B4C44', source:'Bétonel'},
    {code:'DLX1199-6', nom:'Brown Clay',                       hex:'#C37C59', source:'Bétonel'},
    {code:'DLX1059-5', nom:'Ferris Wheel',                     hex:'#AD7D76', source:'Bétonel'},

    // === VERTS ===
    {code:'DLX1137-1', nom:'Pluie printanière / Spring Rain',  hex:'#ECF1EC', source:'Bétonel'},
    {code:'DLX1141-1', nom:'Ice Floe',                         hex:'#D8E7E1', source:'Bétonel'},
    {code:'DLX1141-2', nom:'Green Wave',                       hex:'#C3DCD5', source:'Bétonel'},
    {code:'DLX1141-3', nom:'Cassiopeia',                       hex:'#AED0C9', source:'Bétonel'},
    {code:'DLX1141-4', nom:'Caribbean Green',                  hex:'#89BAB2', source:'Bétonel'},
    {code:'DLX1141-5', nom:'Treasure Isle',                    hex:'#609D91', source:'Bétonel'},
    {code:'DLX1141-6', nom:'Carlisle',                         hex:'#45867C', source:'Bétonel'},
    {code:'DLX1141-7', nom:'Deep Veridian',                    hex:'#116356', source:'Bétonel'},
    {code:'DLX1136-1', nom:'Perle de mer / Sea Pearl',         hex:'#E0E9E4', source:'Bétonel'},
    {code:'DLX1136-2', nom:'Mélodie de la pluie / Rainsong',   hex:'#DEE8E3', source:'Bétonel'},
    {code:'DLX1136-3', nom:'Brise matinale / Morning Breeze',  hex:'#D5E3DE', source:'Bétonel'},
    {code:'DLX1136-4', nom:'Trèfle bleu / Blue Shamrock',      hex:'#BACBC4', source:'Bétonel'},
    {code:'DLX1136-5', nom:"Ombre d'épinette / Spruce Shade",  hex:'#91A49D', source:'Bétonel'},
    {code:'DLX1136-6', nom:'Épinette naine / Dwarf Spruce',    hex:'#71847D', source:'Bétonel'},
    {code:'DLX1136-7', nom:'Dark Green Velvet',                hex:'#4A5B51', source:'Bétonel'},
    {code:'DLX1142-1', nom:'Nuit paisible / Peaceful Night',   hex:'#D6E7E3', source:'Bétonel'},
    {code:'DLX1142-2', nom:'Grand firmament / Big Sky',        hex:'#CDE2DE', source:'Bétonel'},
    {code:'DLX1142-3', nom:'Vert émeraude / Veridian Green',   hex:'#BCD7D4', source:'Bétonel'},
    {code:'DLX1142-4', nom:'Bruissement / Pitter Patter',      hex:'#9BC2BD', source:'Bétonel'},
    {code:'DLX1142-5', nom:'Catalina',                         hex:'#72A49F', source:'Bétonel'},
    {code:'DLX1142-6', nom:'Jade de Jéricho / Jericho Jade',   hex:'#4D8681', source:'Bétonel'},
    {code:'DLX1142-7', nom:'Sarcelle impératrice / Empress Teal', hex:'#10605A', source:'Bétonel'},
    {code:'DLX1143-1', nom:'Bruine délicate / Delicate Mist',  hex:'#E1EBE5', source:'Bétonel'},
    {code:'DLX1143-2', nom:'Berceuse bleue / Blue Lullaby',    hex:'#C8D7D2', source:'Bétonel'},
    {code:'DLX1143-3', nom:'Lutin de mer / Sea Sprite',        hex:'#B7CCC7', source:'Bétonel'},
    {code:'DLX1143-4', nom:'Plume de perroquet / Parakeet Pete', hex:'#94B1A9', source:'Bétonel'},
    {code:'DLX1143-5', nom:'Yucca',                            hex:'#75978F', source:'Bétonel'},
    {code:'DLX1143-6', nom:'Émeraude fumée / Smoky Emerald',   hex:'#4C726B', source:'Bétonel'},
    {code:'DLX1143-7', nom:'Feuille de houx / Holly Leaf',     hex:'#2E5A50', source:'Bétonel'},
    {code:'DLX1144-1', nom:'Morning Fog',                      hex:'#D0DBD7', source:'Bétonel'},
    {code:'DLX1144-2', nom:'Thunder Bay',                      hex:'#CBD9D7', source:'Bétonel'},
    {code:'DLX1144-3', nom:'Babbling Brook',                   hex:'#BECFCD', source:'Bétonel'},
    {code:'DLX1144-4', nom:'Holly Glen',                       hex:'#A2B7B5', source:'Bétonel'},
    {code:'DLX1144-5', nom:'Green Granite',                    hex:'#7C9793', source:'Bétonel'},
    {code:'DLX1144-6', nom:'Evening Emerald',                  hex:'#56736F', source:'Bétonel'},
    {code:'DLX1144-7', nom:'Crystal Ball',                     hex:'#365955', source:'Bétonel'},
    {code:'DLX1146-1', nom:'Menthe légère / Mild Mint',        hex:'#DCE6E3', source:'Bétonel'},
    {code:'DLX1146-2', nom:'Bruine printanière / Spring Mist', hex:'#D3E0DE', source:'Bétonel'},
    {code:'DLX1146-3', nom:'Vert julep / Julep Green',         hex:'#C7DBD9', source:'Bétonel'},
    {code:'DLX1146-4', nom:'Clairière givrée / Frosty Glade',  hex:'#A0C0BF', source:'Bétonel'},
    {code:'DLX1146-5', nom:'Palmier / Palmetto',               hex:'#6D9A9B', source:'Bétonel'},
    {code:'DLX1146-6', nom:'Trèfle chanceux / Lucky Shamrock', hex:'#487A7B', source:'Bétonel'},
    {code:'DLX1146-7', nom:'Bassin émeraude / Emerald Pool',   hex:'#155E60', source:'Bétonel'},
    {code:'DLX1147-1', nom:'Vert camée / Cameo Green',         hex:'#DCE6E5', source:'Bétonel'},
    {code:'DLX1147-2', nom:'Mountain Dew',                     hex:'#CFE2E0', source:'Bétonel'},
    {code:'DLX1147-3', nom:'Misty Aqua',                       hex:'#BCDBDB', source:'Bétonel'},
    {code:'DLX1147-4', nom:'Aqua Fiesta',                      hex:'#8CC3C3', source:'Bétonel'},
    {code:'DLX1147-5', nom:'Teal Bayou',                       hex:'#57A1A0', source:'Bétonel'},
    {code:'DLX1147-6', nom:'Jade Jewel',                       hex:'#247E81', source:'Bétonel'},
    {code:'DLX1147-7', nom:'Tahitian Treat',                   hex:'#00686D', source:'Bétonel'},
    {code:'DLX1148-1', nom:'Meadowsweet Mist',                 hex:'#D4E3E2', source:'Bétonel'},
    {code:'DLX1148-2', nom:'Pistachio Cream',                  hex:'#D5E2E1', source:'Bétonel'},
    {code:'DLX1148-3', nom:'Cosmic Rays',                      hex:'#CADADA', source:'Bétonel'},
    {code:'DLX1148-6', nom:'Vining Ivy',                       hex:'#4B7378', source:'Bétonel'},
    {code:'DLX1229-1', nom:'Wintergreen',                      hex:'#D4EDE3', source:'Bétonel'},
    {code:'DLX1229-2', nom:'Wintergreen Mint',                 hex:'#BDE8D8', source:'Bétonel'},
    {code:'DLX1229-3', nom:'Almost Aqua',                      hex:'#98DDC5', source:'Bétonel'},
    {code:'DLX1229-4', nom:'Tropical Tide',                    hex:'#5ECAAE', source:'Bétonel'},
    {code:'DLX1229-5', nom:'Aloha',                            hex:'#1DB394', source:'Bétonel'},
    {code:'DLX1229-6', nom:'Congo Green',                      hex:'#00A483', source:'Bétonel'},
    {code:'DLX1229-7', nom:'Carolina Green',                   hex:'#008B6D', source:'Bétonel'},
    {code:'DLX1230-1', nom:'Tropical Dream',                   hex:'#D9EAE5', source:'Bétonel'},
    {code:'DLX1230-2', nom:'Serendipity',                      hex:'#BDE1D8', source:'Bétonel'},
    {code:'DLX1230-3', nom:'Whirlpool',                        hex:'#A5D8CD', source:'Bétonel'},
    {code:'DLX1230-4', nom:'Pale Jade',                        hex:'#77C3B4', source:'Bétonel'},
    {code:'DLX1230-5', nom:'Jewel Weed',                       hex:'#46A795', source:'Bétonel'},
    {code:'DLX1230-6', nom:'Miami Jade',                       hex:'#17917F', source:'Bétonel'},
    {code:'DLX1230-7', nom:'Medieval Forest',                  hex:'#007E6B', source:'Bétonel'},

    // === TURQUOISES & TEALS ===
    {code:'DLX1231-1', nom:'Bleu-vert sacré / Hallowed Hush',  hex:'#E2EBE5', source:'Bétonel'},
    {code:'DLX1231-2', nom:'Lac des cygnes / Swan Lake',       hex:'#C5E5E2', source:'Bétonel'},
    {code:'DLX1231-3', nom:'Minerve / Minerva',                hex:'#B5DEDA', source:'Bétonel'},
    {code:'DLX1231-4', nom:'Vacances tropicales / Tropical Holiday', hex:'#8FCDC7', source:'Bétonel'},
    {code:'DLX1231-5', nom:'Puits artésien / Artesian Well',   hex:'#5EB2AA', source:'Bétonel'},
    {code:'DLX1231-6', nom:"Marée d'azur / Azure Tide",        hex:'#2B9890', source:'Bétonel'},
    {code:'DLX1231-7', nom:'Île romantique / Romantic Isle',   hex:'#007C75', source:'Bétonel'},
    {code:'DLX1232-1', nom:'Ice Blue',                         hex:'#E1EDE6', source:'Bétonel'},
    {code:'DLX1232-2', nom:'Cascade',                          hex:'#D4EDE6', source:'Bétonel'},
    {code:'DLX1232-3', nom:'Silent Ripple',                    hex:'#ABE3DE', source:'Bétonel'},
    {code:'DLX1232-4', nom:'Isle Royale',                      hex:'#80D7CF', source:'Bétonel'},
    {code:'DLX1232-5', nom:'Tint Of Turquoise',                hex:'#41BFB5', source:'Bétonel'},
    {code:'DLX1232-6', nom:'Grecian Isle',                     hex:'#00A49B', source:'Bétonel'},
    {code:'DLX1232-7', nom:'Torrid Turquoise',                 hex:'#00938B', source:'Bétonel'},
    {code:'DLX1233-1', nom:'Esprit libre / Free Spirit',       hex:'#DEEEEE', source:'Bétonel'},
    {code:'DLX1233-2', nom:'Embruns marins / Seaspray',        hex:'#D2EBEA', source:'Bétonel'},
    {code:'DLX1233-3', nom:'Écume de mer pâle / Pale Seafoam', hex:'#C3E7E8', source:'Bétonel'},
    {code:'DLX1233-4', nom:'Paysage marin / Seascape Green',   hex:'#B5E4E4', source:'Bétonel'},
    {code:'DLX1233-5', nom:'Touche tropicale / Tropical Splash', hex:'#70CBCE', source:'Bétonel'},
    {code:'DLX1233-6', nom:'Montego Bay',                      hex:'#3FBABD', source:'Bétonel'},
    {code:'DLX1233-7', nom:'Bleu Riviera / Riviera Paradise',  hex:'#009A9E', source:'Bétonel'},
    {code:'DLX1234-1', nom:"Teinte d'eau / Aqua Tint",         hex:'#E5F1EE', source:'Bétonel'},
    {code:'DLX1234-2', nom:'Plateau',                          hex:'#D3E7E5', source:'Bétonel'},
    {code:'DLX1234-3', nom:'Murmure aquatique / Aqua Whisper', hex:'#BFDFDF', source:'Bétonel'},
    {code:'DLX1234-4', nom:'Vert amourette / Fling Green',     hex:'#8ECFD0', source:'Bétonel'},
    {code:'DLX1234-5', nom:'Baie de Biscaye / Biscay Bay',     hex:'#4FB3B3', source:'Bétonel'},
    {code:'DLX1234-6', nom:'Fantaisie de la mer / Sea Fantasy', hex:'#1A9597', source:'Bétonel'},
    {code:'DLX1234-7', nom:'Mer hypnotique / Hypnotic Sea',    hex:'#00787F', source:'Bétonel'},
    {code:'DLX1235-1', nom:'Embrasse-moi / Kiss Me Kate',      hex:'#E8EFEC', source:'Bétonel'},

    // === BLEUS ===
    {code:'DLX1145-1', nom:'Goutte de pluie / Rain Drop',      hex:'#E7EEEE', source:'Bétonel'},
    {code:'DLX1145-2', nom:'Jack Frost',                       hex:'#DAE6E3', source:'Bétonel'},
    {code:'DLX1145-3', nom:'Cave Pearl',                       hex:'#D6E5E2', source:'Bétonel'},
    {code:'DLX1145-5', nom:'Scarborough',                      hex:'#809381', source:'Bétonel'},
    {code:'DLX1145-6', nom:'Juniper Berry',                    hex:'#576B6B', source:'Bétonel'},
    {code:'DLX1145-7', nom:'Night Watch',                      hex:'#3C504F', source:'Bétonel'},
    {code:'DLX1149-1', nom:'Bleu alpin / Alpine Blue',         hex:'#DBE4E5', source:'Bétonel'},
    {code:'DLX1149-2', nom:'High Sierra',                      hex:'#CEE2E2', source:'Bétonel'},
    {code:'DLX1149-3', nom:'Scandinavian Sky',                 hex:'#C2D3D6', source:'Bétonel'},
    {code:'DLX1149-4', nom:'Mountain Stream',                  hex:'#96AFB7', source:'Bétonel'},
    {code:'DLX1149-7', nom:'Blue Bayberry',                    hex:'#2D5360', source:'Bétonel'},
    {code:'DLX1150-2', nom:'Water Lily',                       hex:'#CEE0E3', source:'Bétonel'},
    {code:'DLX1150-3', nom:'Everglade Mist',                   hex:'#B7D7DE', source:'Bétonel'},
    {code:'DLX1150-4', nom:'Kingston Aqua',                    hex:'#8FBCC4', source:'Bétonel'},
    {code:'DLX1150-6', nom:'Bermuda',                          hex:'#1B7D8D', source:'Bétonel'},
    {code:'DLX1150-7', nom:'Caribbean Splash',                 hex:'#00697C', source:'Bétonel'},
    {code:'DLX1151-1', nom:'Beachcomber',                      hex:'#D9E4E5', source:'Bétonel'},
    {code:'DLX1151-2', nom:'Embellishment',                    hex:'#CBDEE2', source:'Bétonel'},
    {code:'DLX1151-3', nom:"Rêve d'été / Midsummer's Dream",   hex:'#B4D0D9', source:'Bétonel'},
    {code:'DLX1151-4', nom:'Crystal Lake',                     hex:'#88B5C4', source:'Bétonel'},
    {code:'DLX1151-5', nom:'Aqua Blue',                        hex:'#5E97A9', source:'Bétonel'},
    {code:'DLX1151-6', nom:'Adventure',                        hex:'#34788C', source:'Bétonel'},
    {code:'DLX1151-7', nom:'Jamaican Dream',                   hex:'#04627A', source:'Bétonel'},
    {code:'DLX1152-1', nom:'Subtle Blue',                      hex:'#D9E3E5', source:'Bétonel'},
    {code:'DLX1152-2', nom:'Breakwater',                       hex:'#D1DEE4', source:'Bétonel'},
    {code:'DLX1152-3', nom:'Graceful',                         hex:'#A8C0CE', source:'Bétonel'},
    {code:'DLX1152-4', nom:'Americana',                        hex:'#7F9DAF', source:'Bétonel'},
    {code:'DLX1152-5', nom:'Granite Falls',                    hex:'#638496', source:'Bétonel'},
    {code:'DLX1152-6', nom:'Brigade',                          hex:'#365D73', source:'Bétonel'},
    {code:'DLX1152-7', nom:'Shimmering Sea',                   hex:'#2B526A', source:'Bétonel'},
    {code:'DLX1153-1', nom:'Ice Castles',                      hex:'#E8EFEC', source:'Bétonel'},
    {code:'DLX1153-2', nom:'Artemesia',                        hex:'#E3EBEA', source:'Bétonel'},
    {code:'DLX1153-3', nom:'Blue Smoke',                       hex:'#D7E0E2', source:'Bétonel'},
    {code:'DLX1153-4', nom:'Chambray',                         hex:'#ADBFC8', source:'Bétonel'},
    {code:'DLX1153-5', nom:'Chalky Blue',                      hex:'#7B8F99', source:'Bétonel'},
    {code:'DLX1153-6', nom:'Silent Night',                     hex:'#526771', source:'Bétonel'},
    {code:'DLX1154-1', nom:'Shooting Star',                    hex:'#ECF0EB', source:'Bétonel'},
    {code:'DLX1154-2', nom:'Aloof',                            hex:'#D4E2E6', source:'Bétonel'},
    {code:'DLX1154-3', nom:'Dartmoor Mist',                    hex:'#CDDCE3', source:'Bétonel'},
    {code:'DLX1154-4', nom:'Twinkle',                          hex:'#ADC6D3', source:'Bétonel'},
    {code:'DLX1154-5', nom:'Serene Stream',                    hex:'#819DAA', source:'Bétonel'},
    {code:'DLX1154-6', nom:'Prussian Blue',                    hex:'#5D7B89', source:'Bétonel'},
    {code:'DLX1154-7', nom:'Regatta Bay',                      hex:'#2D5367', source:'Bétonel'},
    {code:'DLX1155-1', nom:'Summer Shower',                    hex:'#E1EAEC', source:'Bétonel'},
    {code:'DLX1155-2', nom:'Prelude',                          hex:'#DFEBEE', source:'Bétonel'},
    {code:'DLX1156-1', nom:'Austrian Ice',                     hex:'#DEE6E7', source:'Bétonel'},
    {code:'DLX1156-2', nom:'Bit Of Heaven',                    hex:'#CAD7DE', source:'Bétonel'},
    {code:'DLX1156-3', nom:'Always Blue',                      hex:'#A2BACB', source:'Bétonel'},
    {code:'DLX1156-4', nom:'American Anthem',                  hex:'#7595AB', source:'Bétonel'},
    {code:'DLX1156-5', nom:'Smoke Blue',                       hex:'#53778F', source:'Bétonel'},
    {code:'DLX1156-6', nom:'Mountain Lake',                    hex:'#2D5975', source:'Bétonel'},
    {code:'DLX1156-7', nom:'Celestial Blue',                   hex:'#2C4D69', source:'Bétonel'},
    {code:'DLX1157-1', nom:'Glassine',                         hex:'#D7E2E5', source:'Bétonel'},
    {code:'DLX1157-2', nom:'Blue Pearl',                       hex:'#C5D9E3', source:'Bétonel'},
    {code:'DLX1157-3', nom:'Sonata',                           hex:'#ABC8D8', source:'Bétonel'},
    {code:'DLX1157-4', nom:'Arabella',                         hex:'#82ACC4', source:'Bétonel'},
    {code:'DLX1157-5', nom:'Vanity',                           hex:'#5692B2', source:'Bétonel'},
    {code:'DLX1157-6', nom:'Cosmic Dust',                      hex:'#347699', source:'Bétonel'},
    {code:'DLX1157-7', nom:'Blue Flame',                       hex:'#005E88', source:'Bétonel'},
    {code:'DLX1158-1', nom:"Baby's Breath",                    hex:'#D8E4E8', source:'Bétonel'},
    {code:'DLX1158-2', nom:'Magic Wand',                       hex:'#C3D9E4', source:'Bétonel'},
    {code:'DLX1158-3', nom:'Blue Bows',                        hex:'#A4C3D7', source:'Bétonel'},
    {code:'DLX1158-4', nom:'Serene Sea',                       hex:'#78A7C3', source:'Bétonel'},
    {code:'DLX1158-5', nom:'Cosmopolitan',                     hex:'#528BAB', source:'Bétonel'},
    {code:'DLX1158-6', nom:'Blue Oasis',                       hex:'#296D93', source:'Bétonel'},
    {code:'DLX1158-7', nom:'Stunning Sapphire',                hex:'#185887', source:'Bétonel'},
    {code:'DLX1159-1', nom:'Filigrane / Filigree',             hex:'#DFE7E8', source:'Bétonel'},
    {code:'DLX1159-2', nom:'Calm Sea',                         hex:'#C4D3DC', source:'Bétonel'},
    {code:'DLX1159-3', nom:'Heavenly Blue',                    hex:'#A3BBCD', source:'Bétonel'},
    {code:'DLX1159-4', nom:'Walden Pond',                      hex:'#789BB6', source:'Bétonel'},
    {code:'DLX1159-5', nom:'Stormy Ridge',                     hex:'#507B9A', source:'Bétonel'},
    {code:'DLX1159-6', nom:'Animation',                        hex:'#1D5C83', source:'Bétonel'},
    {code:'DLX1159-7', nom:'Singing The Blues',                hex:'#2B4D68', source:'Bétonel'},
    {code:'DLX1160-1', nom:'Harbor Mist',                      hex:'#DAE1E3', source:'Bétonel'},
    {code:'DLX1160-2', nom:'Magical',                          hex:'#C1CEDA', source:'Bétonel'},
    {code:'DLX1160-3', nom:'Rendezvous',                       hex:'#ABBED0', source:'Bétonel'},
    {code:'DLX1160-4', nom:'Kaleidoscope',                     hex:'#8DA8BE', source:'Bétonel'},
    {code:'DLX1160-5', nom:'Blue Beads',                       hex:'#5A809E', source:'Bétonel'},
    {code:'DLX1160-6', nom:'Chinese Porcelain',                hex:'#3A5F7D', source:'Bétonel'},
    {code:'DLX1160-7', nom:'Blue Tang',                        hex:'#2A4B6E', source:'Bétonel'},
    {code:'DLX1161-1', nom:'Paysage urbain / Cityscape',       hex:'#DAE3E7', source:'Bétonel'},
    {code:'DLX1161-2', nom:"C'est La Vie",                     hex:'#BED1E1', source:'Bétonel'},
    {code:'DLX1161-3', nom:'Everlasting',                      hex:'#A1BED9', source:'Bétonel'},
    {code:'DLX1161-4', nom:'Blue Promise',                     hex:'#729CC2', source:'Bétonel'},
    {code:'DLX1161-5', nom:"Ship's Harbor",                    hex:'#4F84AF', source:'Bétonel'},
    {code:'DLX1161-6', nom:'Starry Night',                     hex:'#286492', source:'Bétonel'},
    {code:'DLX1161-7', nom:'Brilliant Blue',                   hex:'#234E86', source:'Bétonel'},
    {code:'DLX1162-1', nom:'Harbor Light',                     hex:'#D7E0E7', source:'Bétonel'},
    {code:'DLX1162-2', nom:'Stratosphere',                     hex:'#C7D3E0', source:'Bétonel'},
    {code:'DLX1162-3', nom:'Blue Thistle',                     hex:'#ADC0D6', source:'Bétonel'},
    {code:'DLX1162-4', nom:'Alaskan Blue',                     hex:'#7E9EC2', source:'Bétonel'},
    {code:'DLX1162-5', nom:'Shrinking Violet',                 hex:'#5D84B1', source:'Bétonel'},
    {code:'DLX1162-6', nom:'Teeny Bikini',                     hex:'#326395', source:'Bétonel'},
    {code:'DLX1162-7', nom:'Dragonfly',                        hex:'#314A76', source:'Bétonel'},
    {code:'DLX1163-1', nom:'Bleu insaisissable / Elusive Blue', hex:'#DDE4E8', source:'Bétonel'},
    {code:'DLX1163-2', nom:'Memory Lane',                      hex:'#C7D1DB', source:'Bétonel'},
    {code:'DLX1163-3', nom:'Pageant Song',                     hex:'#B6C3D1', source:'Bétonel'},
    {code:'DLX1163-4', nom:'Sterling Silver',                  hex:'#9EAFC2', source:'Bétonel'},
    {code:'DLX1163-5', nom:'Silver Blueberry',                 hex:'#6C8096', source:'Bétonel'},
    {code:'DLX1163-6', nom:'Blue Fjord',                       hex:'#4C6177', source:'Bétonel'},
    {code:'DLX1163-7', nom:'Blueberry Pie',                    hex:'#314D67', source:'Bétonel'},
    {code:'DLX1164-1', nom:'Venteux / Windswept',              hex:'#E8ECEE', source:'Bétonel'},
    {code:'DLX1164-2', nom:'Iceberg',                          hex:'#DAE4EE', source:'Bétonel'},
    {code:'DLX1165-1', nom:'January Dawn',                     hex:'#DFE2E5', source:'Bétonel'},
    {code:'DLX1165-2', nom:'Twinkle Blue',                     hex:'#D0D7DF', source:'Bétonel'},
    {code:'DLX1165-3', nom:'Northern Exposure',                hex:'#BFC7D4', source:'Bétonel'},
    {code:'DLX1165-4', nom:'Innuendo',                         hex:'#A4B0C4', source:'Bétonel'},
    {code:'DLX1165-5', nom:'Evening Hush',                     hex:'#7B8CA8', source:'Bétonel'},
    {code:'DLX1165-6', nom:'Stained Glass',                    hex:'#556682', source:'Bétonel'},
    {code:'DLX1166-1', nom:'Étoile brillante / Bright Star',   hex:'#DDE2E6', source:'Bétonel'},
    {code:'DLX1166-2', nom:'Aster Petal',                      hex:'#D4DAE2', source:'Bétonel'},
    {code:'DLX1166-3', nom:'Blue Opal',                        hex:'#BBC6D9', source:'Bétonel'},
    {code:'DLX1166-4', nom:'Fresh Violet',                     hex:'#99AAC8', source:'Bétonel'},
    {code:'DLX1166-5', nom:'Kimono',                           hex:'#6D86B6', source:'Bétonel'},
    {code:'DLX1166-6', nom:'Blue Odyssey',                     hex:'#4F6997', source:'Bétonel'},
    {code:'DLX1166-7', nom:'Daring Indigo',                    hex:'#374874', source:'Bétonel'},
    {code:'DLX1167-1', nom:'Arctic Dawn',                      hex:'#E3E5E8', source:'Bétonel'},
    {code:'DLX1167-2', nom:'Windsor Haze',                     hex:'#DCDFE5', source:'Bétonel'},
    {code:'DLX1167-3', nom:'Debonaire',                        hex:'#CBD0DD', source:'Bétonel'},
    {code:'DLX1167-4', nom:'Lovely Lilac',                     hex:'#A7B0CC', source:'Bétonel'},
    {code:'DLX1167-5', nom:'Skysail Blue',                     hex:'#818DB3', source:'Bétonel'},
    {code:'DLX1167-6', nom:'Blueberry Patch',                  hex:'#627099', source:'Bétonel'},
    {code:'DLX1167-7', nom:'Blue Jewel',                       hex:'#465383', source:'Bétonel'},
    {code:'DLX1237-1', nom:'Bleu timide / Bashful',            hex:'#E3EDED', source:'Bétonel'},
    {code:'DLX1237-2', nom:'Diamond Blue',                     hex:'#CFE4EE', source:'Bétonel'},
    {code:'DLX1237-3', nom:'Ariel',                            hex:'#AED7EA', source:'Bétonel'},
    {code:'DLX1237-4', nom:'Horizon Haze',                     hex:'#80C1E2', source:'Bétonel'},
    {code:'DLX1237-5', nom:'Mystic Blue',                      hex:'#48A8D0', source:'Bétonel'},
    {code:'DLX1237-6', nom:'Bellflower',                       hex:'#1993BE', source:'Bétonel'},
    {code:'DLX1237-7', nom:'Neptune',                          hex:'#007DAC', source:'Bétonel'},
    {code:'DLX1238-1', nom:'Airy',                             hex:'#DAE6E9', source:'Bétonel'},
    {code:'DLX1238-2', nom:'Goddess',                          hex:'#D0E1E8', source:'Bétonel'},
    {code:'DLX1238-3', nom:'Flemish Blue',                     hex:'#ADD0E0', source:'Bétonel'},
    {code:'DLX1238-4', nom:'Harbor Sky',                       hex:'#7EB6D0', source:'Bétonel'},
    {code:'DLX1238-5', nom:'Hush-A-Bye',                       hex:'#5397B7', source:'Bétonel'},
    {code:'DLX1238-6', nom:'Blue Paisley',                     hex:'#2282A8', source:'Bétonel'},
    {code:'DLX1238-7', nom:'Port Au Prince',                   hex:'#006A93', source:'Bétonel'},
    {code:'DLX1239-1', nom:'Wavecrest',                        hex:'#D6E1E4', source:'Bétonel'},
    {code:'DLX1239-2', nom:"Duck's Egg Blue",                  hex:'#CCDfE8', source:'Bétonel'},
    {code:'DLX1239-3', nom:'Windsor Way',                      hex:'#9FC9E4', source:'Bétonel'},
    {code:'DLX1239-4', nom:'Salem Blue',                       hex:'#66A9D3', source:'Bétonel'},
    {code:'DLX1239-5', nom:'Quiet Night',                      hex:'#3E8FBC', source:'Bétonel'},
    {code:'DLX1239-6', nom:'North Sea',                        hex:'#1D78AB', source:'Bétonel'},
    {code:'DLX1239-7', nom:'Rave Regatta',                     hex:'#00619D', source:'Bétonel'},
    {code:'DLX1240-1', nom:'Ocean Breeze',                     hex:'#D3E5EB', source:'Bétonel'},
    {code:'DLX1240-2', nom:'Niagara Falls',                    hex:'#CBE3EE', source:'Bétonel'},
    {code:'DLX1240-3', nom:'Songbird',                         hex:'#A3D1EB', source:'Bétonel'},
    {code:'DLX1240-4', nom:'Xavier Blue',                      hex:'#6AB4E0', source:'Bétonel'},
    {code:'DLX1240-5', nom:'Sorcerer',                         hex:'#3398CE', source:'Bétonel'},
    {code:'DLX1240-6', nom:'Newport Blue',                     hex:'#1C8AC9', source:'Bétonel'},
    {code:'DLX1240-7', nom:'Cobalt Glaze',                     hex:'#0072B5', source:'Bétonel'},
    {code:'DLX1241-1', nom:'First Light',                      hex:'#D9E6EE', source:'Bétonel'},
    {code:'DLX1241-2', nom:'Vitamin Sea',                      hex:'#C8DDEE', source:'Bétonel'},
    {code:'DLX1241-3', nom:'Sweet Dreams',                     hex:'#9BC7EA', source:'Bétonel'},
    {code:'DLX1241-4', nom:'Windjammer',                       hex:'#62A5DF', source:'Bétonel'},
    {code:'DLX1241-5', nom:'Magical Merlin',                   hex:'#3D8ED0', source:'Bétonel'},
    {code:'DLX1241-6', nom:'Electric Blue',                    hex:'#1E80C7', source:'Bétonel'},
    {code:'DLX1241-7', nom:'Cobalt Stone',                     hex:'#0264AE', source:'Bétonel'},
    {code:'DLX1242-1', nom:'First Frost',                      hex:'#DAE3E9', source:'Bétonel'},
    {code:'DLX1242-2', nom:'Touch Of Blue',                    hex:'#C2D7E9', source:'Bétonel'},
    {code:'DLX1242-3', nom:'Viva La Bleu',                     hex:'#97BEE2', source:'Bétonel'},
    {code:'DLX1242-4', nom:'Overcast',                         hex:'#73A3D0', source:'Bétonel'},
    {code:'DLX1242-5', nom:'King Triton',                      hex:'#3C85BE', source:'Bétonel'},
    {code:'DLX1242-6', nom:'Planetarium',                      hex:'#1C70AD', source:'Bétonel'},
    {code:'DLX1242-7', nom:'Suddenly Sapphire',                hex:'#1A5897', source:'Bétonel'},
    {code:'DLX1243-1', nom:'Douce illusion / Sweet Illusion',  hex:'#E0E8EC', source:'Bétonel'},
    {code:'DLX1243-2', nom:'Haunting Hue',                     hex:'#D3E0EC', source:'Bétonel'},
    {code:'DLX1243-3', nom:'Set Sail',                         hex:'#ABCAEA', source:'Bétonel'},
    {code:'DLX1243-4', nom:'Victoria Blue',                    hex:'#7DAEE1', source:'Bétonel'},
    {code:'DLX1243-5', nom:'Blue Dart',                        hex:'#518FD1', source:'Bétonel'},
    {code:'DLX1243-6', nom:'Royal Plume',                      hex:'#3C7AC2', source:'Bétonel'},
    {code:'DLX1243-7', nom:'Rainbow Bright',                   hex:'#2863AD', source:'Bétonel'},
    {code:'DLX1244-1', nom:'Abyss',                            hex:'#DFE6EA', source:'Bétonel'},
    {code:'DLX1244-2', nom:'Blue Silk',                        hex:'#D0DCE8', source:'Bétonel'},
    {code:'DLX1244-3', nom:'Valor',                            hex:'#A3BCDB', source:'Bétonel'},
    {code:'DLX1244-4', nom:'Boudoir Blue',                     hex:'#7EA3D2', source:'Bétonel'},
    {code:'DLX1244-5', nom:'Blueberry Popover',                hex:'#5488C0', source:'Bétonel'},
    {code:'DLX1244-6', nom:'Nocturne Shade',                   hex:'#356FAD', source:'Bétonel'},
    {code:'DLX1244-7', nom:'Florentine Lapis',                 hex:'#1C5798', source:'Bétonel'},

    // === BLEU-GRIS & ARDOISE ===
    {code:'DLX1034-1', nom:'Morning Song',                     hex:'#E4ECE9', source:'Bétonel'},
    {code:'DLX1034-2', nom:'Honesty',                          hex:'#DFEBE9', source:'Bétonel'},
    {code:'DLX1034-3', nom:'Pristine Petal',                   hex:'#D5E1E0', source:'Bétonel'},
    {code:'DLX1034-5', nom:'Aqua Smoke',                       hex:'#8C9FA0', source:'Bétonel'},
    {code:'DLX1034-6', nom:'Blue Blood',                       hex:'#6B7F81', source:'Bétonel'},
    {code:'DLX1034-7', nom:'Mountain Pine',                    hex:'#3B5257', source:'Bétonel'},
    {code:'DLX1035-1', nom:'Watery Blue',                      hex:'#CFDFDD', source:'Bétonel'},
    {code:'DLX1035-2', nom:'Sky Diving',                       hex:'#C6D6D7', source:'Bétonel'},
    {code:'DLX1035-3', nom:'Blue By You',                      hex:'#A0B7BA', source:'Bétonel'},
    {code:'DLX1035-4', nom:'Symphony Of Blue',                 hex:'#89A0A6', source:'Bétonel'},
    {code:'DLX1035-5', nom:'Puddle Jumper',                    hex:'#6A8389', source:'Bétonel'},
    {code:'DLX1035-6', nom:'Superstition',                     hex:'#5B6E74', source:'Bétonel'},
    {code:'DLX1035-7', nom:'Obsidian',                         hex:'#445055', source:'Bétonel'},
    {code:'DLX1036-2', nom:'Winter Chill',                     hex:'#C9D2D1', source:'Bétonel'},
    {code:'DLX1036-3', nom:'Nautical Star',                    hex:'#AAB5B7', source:'Bétonel'},
    {code:'DLX1036-4', nom:'After The Storm',                  hex:'#919FA1', source:'Bétonel'},
    {code:'DLX1036-5', nom:'Rough Ride',                       hex:'#7A8687', source:'Bétonel'},
    {code:'DLX1036-6', nom:'Phantom',                          hex:'#6E797B', source:'Bétonel'},
    {code:'DLX1036-7', nom:'Mostly Metal',                     hex:'#575E5F', source:'Bétonel'},
    {code:'DLX1037-1', nom:'Sea Frost',                        hex:'#D5DCDC', source:'Bétonel'},
    {code:'DLX1037-4', nom:'Symmetry',                         hex:'#8FA0A7', source:'Bétonel'},
    {code:'DLX1037-6', nom:'Mysterious',                       hex:'#535E63', source:'Bétonel'},
    {code:'DLX1037-7', nom:'Witchcraft',                       hex:'#474C50', source:'Bétonel'},
    {code:'DLX1040-1', nom:'Zen',                              hex:'#CFD9DE', source:'Bétonel'},
    {code:'DLX1040-5', nom:'Lost At Sea',                      hex:'#8D9CA7', source:'Bétonel'},

    // === VIOLETS ===
    {code:'DLX1046-7', nom:'Purple Basil',                     hex:'#5C4450', source:'Bétonel'},
    {code:'DLX1053-7', nom:'Burgundy Wine',                    hex:'#6C403E', source:'Bétonel'},

    // === FALLBACK QUÉBEC EXTÉRIEUR ===
    {code:'DLX0993-1', nom:'Blanc pur',                        hex:'#F5F5F0', source:'Bétonel'},
    {code:'DLX1003-2', nom:"Nuage d'hiver",                    hex:'#E8E4DA', source:'Bétonel'},
    {code:'DLX1151-3B',nom:'Minuit Arctique',                  hex:'#3A3F47', source:'Bétonel'},
    {code:'DLX1071-6', nom:'Taupe classique',                  hex:'#8C7B6B', source:'Bétonel'},
    {code:'DLX1108-5', nom:'Vert sauge',                       hex:'#7A8B72', source:'Bétonel'},
  ];

  var SHERWIN = [
    // === NEUTRES POPULAIRES ===
    {code:'SW 7006', nom:'Extra White',           hex:'#F4F1EB', source:'Sherwin Williams'},
    {code:'SW 7008', nom:'Alabaster',             hex:'#EDEADE', source:'Sherwin Williams'},
    {code:'SW 7012', nom:'Creamy',                hex:'#EFE8D1', source:'Sherwin Williams'},
    {code:'SW 7015', nom:'Repose Gray',           hex:'#C2BDB6', source:'Sherwin Williams'},
    {code:'SW 7016', nom:'Mindful Gray',          hex:'#B7B3A8', source:'Sherwin Williams'},
    {code:'SW 7029', nom:'Agreeable Gray',        hex:'#D3C9BC', source:'Sherwin Williams'},
    {code:'SW 7036', nom:'Accessible Beige',      hex:'#C9B99A', source:'Sherwin Williams'},
    {code:'SW 7039', nom:'Virtual Taupe',         hex:'#C5B9A9', source:'Sherwin Williams'},
    {code:'SW 7040', nom:'Smokehouse',            hex:'#9E968B', source:'Sherwin Williams'},
    {code:'SW 7042', nom:'Shoji White',           hex:'#E0D9CD', source:'Sherwin Williams'},
    {code:'SW 7043', nom:'Worldly Gray',          hex:'#C9C3B8', source:'Sherwin Williams'},
    {code:'SW 7044', nom:'Amazing Gray',          hex:'#BCB8AE', source:'Sherwin Williams'},
    {code:'SW 7048', nom:'Urban Bronze',          hex:'#756960', source:'Sherwin Williams'},
    {code:'SW 7060', nom:'Attitude Gray',         hex:'#A09A94', source:'Sherwin Williams'},
    {code:'SW 7063', nom:'Nebulous White',        hex:'#DDD9D0', source:'Sherwin Williams'},
    {code:'SW 7064', nom:'Passive',               hex:'#C5C6BF', source:'Sherwin Williams'},
    {code:'SW 7066', nom:'Gray Matters',          hex:'#B0AEAA', source:'Sherwin Williams'},
    {code:'SW 7069', nom:'Iron Ore',              hex:'#4B4B4B', source:'Sherwin Williams'},
    {code:'SW 7670', nom:'Argos',                 hex:'#BDB8B0', source:'Sherwin Williams'},

    // === BLANCS ===
    {code:'SW 7550', nom:'Antique White',         hex:'#F0EAD6', source:'Sherwin Williams'},
    {code:'SW 7551', nom:'Greek Villa',           hex:'#EDE8DA', source:'Sherwin Williams'},
    {code:'SW 7652', nom:'Navajo White',          hex:'#EFE0C8', source:'Sherwin Williams'},
    {code:'SW 7104', nom:'Antique White (Deep)',  hex:'#ECE0CC', source:'Sherwin Williams'},
    {code:'SW 6119', nom:'Divine White',          hex:'#EDE8DF', source:'Sherwin Williams'},
    {code:'SW 6385', nom:'Origami White',         hex:'#EFE9DA', source:'Sherwin Williams'},

    // === BEIGES & TAUPES ===
    {code:'SW 6038', nom:'Linen White',           hex:'#EDE5D4', source:'Sherwin Williams'},
    {code:'SW 7526', nom:'Cordovan',              hex:'#7B5241', source:'Sherwin Williams'},
    {code:'SW 7533', nom:'Khaki Shade',           hex:'#B5A48B', source:'Sherwin Williams'},
    {code:'SW 9173', nom:'Oyster Bay',            hex:'#B8C4BF', source:'Sherwin Williams'},

    // === GRIS FONCÉS & CHARBONS ===
    {code:'SW 7672', nom:'Peppercorn',            hex:'#595650', source:'Sherwin Williams'},
    {code:'SW 7674', nom:'Dovetail',              hex:'#877D74', source:'Sherwin Williams'},
    {code:'SW 6990', nom:'Black of Night',        hex:'#2F2E2C', source:'Sherwin Williams'},
    {code:'SW 6991', nom:'Black Magic',           hex:'#2A2B2A', source:'Sherwin Williams'},
    {code:'SW 7068', nom:'Grizzle Gray',          hex:'#737369', source:'Sherwin Williams'},
    {code:'SW 7017', nom:'Porpoise',              hex:'#9B938D', source:'Sherwin Williams'},

    // === BLEUS ===
    {code:'SW 6218', nom:'Liveable Green',        hex:'#8C9B82', source:'Sherwin Williams'},
    {code:'SW 6217', nom:'Lively Yellow',         hex:'#C2B976', source:'Sherwin Williams'},
    {code:'SW 6244', nom:'Waterloo',              hex:'#5C6E7E', source:'Sherwin Williams'},
    {code:'SW 6508', nom:'Rarified Air',          hex:'#C7D4DA', source:'Sherwin Williams'},
    {code:'SW 6781', nom:'Misty',                 hex:'#CED8DC', source:'Sherwin Williams'},
    {code:'SW 6788', nom:'Blustery Sky',          hex:'#6E8FA5', source:'Sherwin Williams'},
    {code:'SW 7517', nom:"River's Edge",          hex:'#A8B0A8', source:'Sherwin Williams'},
    {code:'SW 7641', nom:'Jubilee',               hex:'#6E7E88', source:'Sherwin Williams'},

    // === VERTS ===
    {code:'SW 6148', nom:'Shagreen',              hex:'#819580', source:'Sherwin Williams'},
    {code:'SW 6183', nom:'Rosemary',              hex:'#6D7D6B', source:'Sherwin Williams'},
    {code:'SW 6192', nom:'Clary Sage',            hex:'#9FAA8E', source:'Sherwin Williams'},
    {code:'SW 6204', nom:'Succulent',             hex:'#76887B', source:'Sherwin Williams'},
    {code:'SW 6216', nom:'Evergreens',            hex:'#4A6350', source:'Sherwin Williams'},
    {code:'SW 6461', nom:'Topiary Tint',          hex:'#BECAB5', source:'Sherwin Williams'},
    {code:'SW 7738', nom:'Basil',                 hex:'#4E6050', source:'Sherwin Williams'},

    // === TENDANCE 2024-2026 ===
    {code:'SW 9137', nom:'Drift of Mist',         hex:'#D8D5CF', source:'Sherwin Williams'},
    {code:'SW 9541', nom:'Drift of Mist (Light)', hex:'#E1DED9', source:'Sherwin Williams'},
    {code:'SW 9166', nom:'Drift of Mist (Dark)',  hex:'#CCCAC4', source:'Sherwin Williams'},
    {code:'SW 7637', nom:'Mineral Deposit',       hex:'#7F8D8E', source:'Sherwin Williams'},
    {code:'SW 6001', nom:'Grayish',               hex:'#BFC0BA', source:'Sherwin Williams'},
    {code:'SW 7651', nom:'Front Porch',           hex:'#EDE3D0', source:'Sherwin Williams'},
    {code:'SW 9080', nom:'Pewter Cast',           hex:'#B2ABA1', source:'Sherwin Williams'},
    {code:'SW 9081', nom:'Elusive Gray',          hex:'#C9C5BC', source:'Sherwin Williams'},
    {code:'SW 6253', nom:'Olympus White',         hex:'#DDE3E5', source:'Sherwin Williams'},

    // === ROUGES & BORDEAUX ===
    {code:'SW 6323', nom:'Dishy Coral',           hex:'#E8907A', source:'Sherwin Williams'},
    {code:'SW 6868', nom:'Antler Velvet',         hex:'#8B6652', source:'Sherwin Williams'},
    {code:'SW 7593', nom:'Antique Red',           hex:'#8B3A3A', source:'Sherwin Williams'},
    {code:'SW 6861', nom:'Heartthrob',            hex:'#A53939', source:'Sherwin Williams'},
  ];

  // Fusionner avec window.COULEURS existant (défini dans le HTML)
  if (typeof window !== 'undefined') {
    if (typeof window.COULEURS !== 'undefined' && Array.isArray(window.COULEURS)) {
      window.COULEURS = window.COULEURS.concat(BETONEL).concat(SHERWIN);
    } else {
      window.COULEURS = BETONEL.concat(SHERWIN);
    }
  }
})();
